deps:
  twig:
    twig:
      url: https://github.com/fabpot/Twig
      #scm: git
      #version: xxx
  monolog:
    monolog:
      url: https://github.com/Seldaek/monolog.git
  doctrine-dbal:
    doctrine-common:
      url: https://github.com/doctrine/common
    doctrine-dbal:
      url: https://github.com/doctrine/dbal