deps:
  twig:
    url: https://github.com/fabpot/Twig
    #scm: git
    #version: xxx
    providers: [twig]
  monolog:
    url: https://github.com/Seldaek/monolog.git
    providers: [monolog]
  doctrine-common:
    url: https://github.com/doctrine/common
    providers: [doctrine-dbal, doctrine-orm]
    version: origin/2.1.x
  doctrine-dbal:
    url: https://github.com/doctrine/dbal.git
    providers: [doctrine-dbal]
    version: origin/2.1.x
  doctrine-orm:
    url: https://github.com/doctrine/doctrine2.git
    providers: [doctrine-orm]
    version: origin/2.1.x