deps:
  twig:
    url: https://github.com/fabpot/Twig
    #scm: git
    #version: xxx
    providers: [twig]
  monolog:
    url: https://github.com/Seldaek/monolog.git
    providers: [monolog]
  doctrine-common:
    url: https://github.com/doctrine/common
    providers: [doctrine-dbal]
  doctrine-dbal:
    url: https://github.com/doctrine/dbal
    providers: [doctrine-dbal]